# Generated by Django 2.0.4 on 2018-04-19 23:17

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_owner', models.CharField(max_length=254)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.TextField(blank=True)),
                ('brand_color', models.CharField(blank=True, max_length=25, null=True)),
                ('content_blurb', models.TextField(blank=True)),
                ('content_brand', models.TextField(blank=True)),
                ('sub_title', models.TextField(blank=True)),
                ('sub_content', models.TextField(blank=True)),
                ('sub_text_color', models.CharField(blank=True, max_length=25, null=True)),
                ('image_thumbnail', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('image_header', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('image_about', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('image_brand', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BrandTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_by', models.CharField(max_length=254)),
                ('content', models.TextField(blank=True)),
                ('image_testimonial', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarriorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=general.models.upload_location, width_field='width_field')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarriorVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('wistia_id', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
