# Generated by Django 2.0.4 on 2018-04-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='content_brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_content',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_title',
        ),
    ]
