# Generated by Django 2.0.4 on 2018-04-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20180420_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warrior',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='WarriorImage',
            new_name='WarriorMediaImage',
        ),
        migrations.RenameModel(
            old_name='WarriorVideo',
            new_name='WarriorMediaVideo',
        ),
    ]
