# Generated by Django 2.0.4 on 2018-04-20 16:27

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20180420_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_about',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_brand',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_header',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_text_color',
        ),
        migrations.AlterField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.upload_location),
        ),
        migrations.AlterField(
            model_name='brandtestimonial',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandtestimonial',
            name='image_testimonial',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.upload_location),
        ),
        migrations.AlterField(
            model_name='brandtestimonial',
            name='testimonial_by',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.upload_location),
        ),
        migrations.AlterField(
            model_name='warriormediaimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.upload_location),
        ),
        migrations.AlterField(
            model_name='warriormediavideo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
