# Generated by Django 2.0.4 on 2018-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20180430_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriormediaimage',
            name='display_order',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='display_order',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
