# Generated by Django 2.0.4 on 2018-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20180508_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriormediaimage',
            name='department',
            field=models.CharField(choices=[('None', 'N/A'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Production', 'Production'), ('Customer Service', 'Customer Service'), ('Accounting', 'Accounting')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='warriormediaimage',
            name='executive',
            field=models.BooleanField(default=False),
        ),
    ]
