# Generated by Django 2.0.4 on 2018-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20180615_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('None', 'Not Applicable'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Production', 'Production'), ('Customer Service', 'Customer Service'), ('Accounting', 'Accounting')], default='Not Applicable', max_length=50),
        ),
    ]
