# Generated by Django 2.0.4 on 2018-06-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20180615_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('None', 'Not Applicable'), ('Accounting', 'Accounting'), ('Administrative', 'Administrative'), ('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('Production', 'Production'), ('Tech', 'Tech')], default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='warriormediaimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
