# Generated by Django 2.0.4 on 2018-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20180615_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('None', 'Not Applicable'), ('Accounting', 'Accounting'), ('Content', 'Content'), ('Customer Experience', 'Customer Experience'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Production', 'Production'), ('Tech', 'Tech')], default='Not Applicable', max_length=50),
        ),
    ]
